//Cera Oh. Fall 2021 CS541 AI.
//Prog2 Genetic Algorithm for 8-Queens Problem
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <sys/time.h>

typedef struct agent{//Represents agent with five sensors, Current, N, S, E, W. 0 = empty, 1 = can, -1 = wall.
 int Current;
 int North;
 int South;
 int East;
 int West;
 int reward;
 int row;//Row Robby is in
 int col;//Column Robby is in
}Robot;

Robot move_N(Robot Robby)
{
    if (Robby.North == -1)//Wall
    {
        Robby.reward = Robby.reward -5;
        printf("Robby ran into a North wall and bounced back to [%d][%d] \n", Robby.row, Robby.col);
    }
    else if (Robby.North == 0 || Robby.North == 1) //No wall
    {
        Robby.row = Robby.row - 1;
        printf("Robby moved North to [%d][%d] \n", Robby.row, Robby.col);
    }
    else
    {
        printf("Error moving N :( \n");
    }
    return Robby;
}

Robot move_S(Robot Robby)
{
    if (Robby.South == -1)//Wall
    {
        Robby.reward = Robby.reward -5;
        printf("Robby ran into a South wall and bounced back to [%d][%d] \n", Robby.row, Robby.col);
    }
    else if (Robby.South == 0 || Robby.South == 1) //No wall
    {
        Robby.row = Robby.row + 1;
        printf("Robby moved South to [%d][%d] \n", Robby.row, Robby.col);
    }
    else
    {
        printf("Error moving S :( \n");
    }
    return Robby;
}

Robot move_W(Robot Robby)
{
    if (Robby.West == -1)//Wall
    {
        Robby.reward = Robby.reward -5;
        printf("Robby ran into a West wall and bounced back to [%d][%d] \n", Robby.row, Robby.col);
    }
    else if (Robby.West == 0 || Robby.West == 1) //No wall
    {
        Robby.col = Robby.col - 1;
        printf("Robby moved West to [%d][%d] \n", Robby.row, Robby.col);
    }
    else
    {
        printf("Error moving W :( \n");
    }
    return Robby;
}

Robot move_E(Robot Robby)
{
    if (Robby.East == -1)//Wall
    {
        Robby.reward = Robby.reward -5;
        printf("Robby ran into a East wall and bounced back to [%d][%d] \n", Robby.row, Robby.col);
    }
    else if (Robby.East == 0 || Robby.East == 1) //No wall
    {
        Robby.col = Robby.col + 1;
        printf("Robby moved East to [%d][%d] \n", Robby.row, Robby.col);
    }
    else
    {
        printf("Error moving E :( \n");
    }
    return Robby;
}

Robot pick_up(Robot Robby, int board[10][10])
{
    if (board[Robby.row][Robby.col] == 1)//There's a can
    {
        Robby.reward = Robby.reward + 10;
        board[Robby.row][Robby.col] = 0;
        printf("Robby picked up a can :) \n");
    }
    else if (board[Robby.row][Robby.col] == 0) //No can
    {
        Robby.reward = Robby.reward - 1;
        printf("Robby attempted to pick up a can...but there was nothing :( \n");
    }
    else
    {
        printf("Error picking up can :( \n");
    }
    return Robby;
}

int board_ini (int num)
{
    int chosen;//Number generated by rand()
    int seed = 0;
    int size = 2;//Max range of numbers rand() will pick from for can placement.
    struct timeval seeder;

    gettimeofday (&seeder, NULL);
    seed = seeder.tv_usec + num;
    srand(seed);
    chosen = rand() % size;

   return chosen;
}

int* robby_ini (int* position)
{

    int robby_i;//row position for Robby
    int robby_j;//column position for Robby
    int seed = 0;
    int r_size = 10;//Max range of numbers rand() will pick from for Robby's row/col position
    struct timeval seeder;

    gettimeofday (&seeder, NULL);
    seed = seeder.tv_usec;
    srand(seed + 4);

    robby_i = rand() % r_size;

    srand(seed + 15);//seeds rand()
    robby_j = rand() % r_size;

    position[0] = robby_i;
    position[1] = robby_j;

    return position;
}

Robot Update_Sensors (Robot Robby, int board[10][10])//Updates sensors and reward info for Robby
{                                                                      // 1 = can, 0 = empty, -1 = wall
//Update Current
    if (board[Robby.row][Robby.col] == 1)
    {
        Robby.Current = 1;//There is a can at current location
    }
    else if (board[Robby.row][Robby.col] == 0)
    {
        Robby.Current = 0;//No can at current location
    }
//Update North Sensor
    if ((Robby.row - 1) >= 0 && (Robby.row - 1) <= 9)//valid value for N: between 0 and 9
    {
        if (board[Robby.row - 1][Robby.col] == 1)
        {
            Robby.North = 1;//There is a can at N
        }
        else if (board[Robby.row - 1][Robby.col] == 0)
        {
        Robby.North = 0;//No can at N
        }
    }
    else
    {
        Robby.North = -1;//Wall at N
    }
//Update South Sensor
 int South;
    if ((Robby.row + 1) >= 0 && (Robby.row + 1) <= 9)//valid value for S: between 0 and 9
    {
        if (board[Robby.row + 1][Robby.col] == 1)
        {
            Robby.South = 1;//Can at S
        }
        else if (board[Robby.row + 1][Robby.col] == 0)
        {
        Robby.South = 0;//No can at S
        }
    }
    else
    {
        Robby.South = -1;//Wall at S
    }
//Update West Sensor
    if ((Robby.col - 1) >= 0 && (Robby.col - 1) <= 9)//valid value for W: between 0 and 9
    {
        if (board[Robby.row][Robby.col - 1] == 1)
        {
            Robby.West = 1;//Can at W
        }
        else if (board[Robby.row][Robby.col - 1] == 0)
        {
        Robby.West = 0;//No can at W
        }
    }
    else
    {
        Robby.West = -1;//Wall at W
    }
//Update East Sensor
    if ((Robby.col + 1) >= 0 && (Robby.col + 1) <= 9)//valid value for E: between 0 and 9
    {
        if (board[Robby.row][Robby.col + 1] == 1)
        {
            Robby.East = 1;//Can at E
        }
        else if (board[Robby.row][Robby.col + 1] == 0)
        {
        Robby.East = 0;//No can at E
        }
    }
    else
    {
        Robby.East = -1;//Wall at E
    }

    return Robby;
}

void Q_Learning (float matrix[100][5])
{
    //int N = 5000;
   // int M = 200;
    //int alpha = 0.2;
    //int gamma = 0.9;
    matrix[0][0] = 34.535;
    printf("%x \n", &matrix[0][0]);
    //Q(st, at) = Q(st, at) + 0.2[r(t+1) + 0.9maxQ(s(t+1), at - Q(st+ at)]
}
void print_board(int board[10][10], Robot Robby)//prints 10x10 board
{
    printf(" -----------------------------------------\n");
    for (int i = 0; i < 10; i++)
    {
        printf("%d|", i);
        for (int j = 0; j < 10; j++)
        {
            if (board[i][j] == 1 && (Robby.row != i || Robby.col != j))
            {
                printf(" c |");//can
            }
            else if (board[i][j] == 1 && (Robby.row == i && Robby.col == j))
            {
                printf(" Rc|");//Robby
            }
            else if (board[i][j] == 0 && (Robby.row == i && Robby.col == j))
            {
                printf(" R |");//Robby
            }
            else
            {
                printf("   |");
            }
        }
        printf("\n");
        printf(" -----------------------------------------\n");
    }
        printf("   0   1   2   3   4   5   6   7   8   9  \n");
}

void print_Q(float matrix[100][5])//prints Q_Matrix
{
    int counter = 0;
    int k = 0;
    int l = 0;
    printf("Printing Q-Matrix: \n");
    printf(" Matrix |\tNorth    |\tSouth    |\tWest     |\tEast     |\tPick Up   \n");
    printf("-------------------------------------------------------------------------------------------\n");
    for (int i = 0; i < 100; i++)
    {
        printf(" [%d][%d] |", l, k);
        for(int j = 0; j < 5; j++)
        {

            printf("\t%f |", matrix[i][j]);
        }
        k++;
        if (k == 10)
        {
            l++;
            k = 0;
        }
        printf("\n");
        printf("-------------------------------------------------------------------------------------------\n");
    }
}

void print_Robby(Robot Robby)
{
    printf("Robby's Stats: \n");
    printf("Robby is at [%d][%d] \n", Robby.row,Robby.col);
    if (Robby.Current == 1)
    {
        printf("Current: Can \n");
    }
    else if (Robby.Current == 0)
    {
        printf("Current: Empty \n");
    }
    else
    {
        printf("Current Sensor failed :(\n");
    }

    if (Robby.North == 1)
    {
        printf("North: Can \n");
    }
    else if (Robby.North == 0)
    {
        printf("North: Empty \n");
    }
    else if (Robby.North == -1)
    {
        printf("North: Wall \n");
    }
    else
    {
        printf("North Sensor failed :(\n");
    }

    if (Robby.South == 1)
    {
        printf("South: Can \n");
    }
    else if (Robby.South == 0)
    {
        printf("South: Empty \n");
    }
    else if (Robby.South == -1)
    {
        printf("South: Wall \n");
    }
    else
    {
        printf("South Sensor failed :(\n");
    }

    if (Robby.West == 1)
    {
        printf("West: Can \n");
    }
    else if (Robby.West == 0)
    {
        printf("West: Empty \n");
    }
    else if (Robby.West == -1)
    {
        printf("West: Wall \n");
    }
    else
    {
        printf("West Sensor failed :(\n");
    }

    if (Robby.East == 1)
    {
        printf("East: Can \n");
    }
    else if (Robby.East == 0)
    {
        printf("East: Empty \n");
    }
    else if (Robby.East == -1)
    {
        printf("East: Wall \n");
    }
    else
    {
        printf("East Sensor failed :(\n");
    }

    printf("Reward: %d \n", Robby.reward);
    printf("\n");
}

int main ()
{
    int board [10][10];//Creates 10x10 board world for Robby and cans
    float Q_Matrix [100][5] = {0};//Q-Matrix for Robby, initialized to 0.
    Robot Robby;//Robby created
    int can;//Number generated by rand() to determine whether there should be a can on a grid
    int num = 10;
    int* position;
    position = malloc(2*sizeof(int));

    for (int i = 0; i < 10; i++)//initializes the board with cans
    {
        for (int j = 0; j < 10; j++)
        {
            can = board_ini(num);
            num++;
            if (can == 1)
            {
                board[i][j] = 1;
            }
            else
            {
                board[i][j] = 0;
            }
        }
    }
    position = robby_ini(position);
    Robby.row = position[0];
    Robby.col = position[1];
    Robby = Update_Sensors(Robby, board);//initializes Robby's sensors
    Robby.reward = 0;//initializes reward

    print_board(board, Robby);
    print_Robby(Robby);

    Robby = move_N(Robby);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    Robby = pick_up(Robby, board);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    Robby = move_W(Robby);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    Robby = move_S(Robby);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    Robby = pick_up(Robby, board);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    Robby = move_E(Robby);
    Robby = Update_Sensors(Robby, board);
    print_board(board, Robby);
    print_Robby(Robby);

    print_Q(Q_Matrix);
    Q_Learning (Q_Matrix);
    print_Q(Q_Matrix);
    printf("%x", &Q_Matrix[0][0]);
    return (EXIT_SUCCESS);
}
